import express from 'express';
import jwt from 'jsonwebtoken';
import { Stay } from '../models/index.js';
import { generateQRDataURL } from '../utils/qr.js';

const router = express.Router();

/**
 * POST /api/stays
 * Creates a new Stay document
 * Generates JWT token with stay details and saves to Stay.qrToken
 */
router.post('/', async (req, res) => {
  try {
    const { roomNumber, checkIn, checkOut } = req.body;

    // Validate input
    if (!roomNumber || !checkIn || !checkOut) {
      return res.status(400).json({ 
        error: 'roomNumber, checkIn, and checkOut are required' 
      });
    }

    // Validate dates
    const checkInDate = new Date(checkIn);
    const checkOutDate = new Date(checkOut);
    
    if (isNaN(checkInDate.getTime()) || isNaN(checkOutDate.getTime())) {
      return res.status(400).json({ error: 'Invalid date format' });
    }

    if (checkOutDate <= checkInDate) {
      return res.status(400).json({ error: 'checkOut must be after checkIn' });
    }

    // Create stay document (stayId is auto-generated by default)
    const stay = new Stay({
      roomNumber,
      checkIn: checkInDate,
      checkOut: checkOutDate,
      active: true
    });

    // Generate JWT token containing stay details
    const token = jwt.sign(
      {
        stayId: stay.stayId,
        roomNumber: stay.roomNumber,
        checkIn: stay.checkIn,
        checkOut: stay.checkOut
      },
      process.env.JWT_SECRET,
      { expiresIn: '30d' } // Token valid for max stay duration
    );

    // Save token to stay
    stay.qrToken = token;
    await stay.save();

    return res.status(201).json({
      stayId: stay.stayId,
      qrToken: stay.qrToken,
      roomNumber: stay.roomNumber,
      checkIn: stay.checkIn,
      checkOut: stay.checkOut
    });
  } catch (error) {
    console.error('Error creating stay:', error);
    return res.status(500).json({ error: 'Failed to create stay' });
  }
});

/**
 * GET /api/stays
 * Returns all stays for dashboard listing
 */
router.get('/', async (req, res) => {
  try {
    const stays = await Stay.find().sort({ createdAt: -1 });
    return res.json(stays);
  } catch (error) {
    console.error('Error fetching stays:', error);
    return res.status(500).json({ error: 'Failed to fetch stays' });
  }
});

/**
 * GET /api/stays/:stayId/qr
 * Generates a QR code image containing the stay's JWT token
 * Returns base64 data URL of PNG QR code
 */
  router.get('/:stayId/qr', async (req, res) => {
  try {
    const { stayId } = req.params;

    const stay = await Stay.findOne({ stayId });

    if (!stay) {
      return res.status(404).json({ error: 'Stay not found' });
    }

    // Generate QR code from the JWT token
    const qrDataURL = await generateQRDataURL(stay.qrToken);

    return res.json({ qrCode: qrDataURL, stayId });
  } catch (error) {
    console.error('Error generating QR code:', error);
    return res.status(500).json({ error: 'Failed to generate QR code' });
  }
});

/**
 * PATCH /api/stays/:stayId/end
 * Sets Stay.active = false
 */
router.patch('/:stayId/end', async (req, res) => {
  try {
    const { stayId } = req.params;

    const stay = await Stay.findOneAndUpdate(
      { stayId },
      { active: false },
      { new: true }
    );

    if (!stay) {
      return res.status(404).json({ error: 'Stay not found' });
    }

    return res.json({ ended: true, stay });
  } catch (error) {
    console.error('Error ending stay:', error);
    return res.status(500).json({ error: 'Failed to end stay' });
  }
 });

 /**
 * DELETE /api/stays/:stayId
 * Deletes the stay document
 */
router.delete('/:stayId', async (req, res) => {
  try {
    const { stayId } = req.params;

    const stay = await Stay.findOneAndDelete({ stayId });

    if (!stay) {
      return res.status(404).json({ error: 'Stay not found' });
    }

    return res.json({ deleted: true, stayId });
  } catch (error) {
    console.error('Error deleting stay:', error);
    return res.status(500).json({ error: 'Failed to delete stay' });
  }
});

export default router;
